# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GPIO_Proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10GPIO_Proto.proto\x1a\x0cnanopb.proto\"\x8a\x01\n\x0bGPIO_Config\x12\x1d\n\tgpio_func\x18\x01 \x02(\x0e\x32\n.GPIO_FUNC\x12\x1f\n\ngpio_vssel\x18\x02 \x02(\x0e\x32\x0b.GPIO_VSSEL\x12\x1b\n\x08gpio_pad\x18\x03 \x02(\x0e\x32\t.GPIO_PAD\x12\x1e\n\x07int_pol\x18\x04 \x01(\x0e\x32\r.GPIO_INT_POL\"\x8e\x01\n\nGPIO_Proto\x12\x10\n\x08gpio_num\x18\x01 \x02(\r\x12\x1c\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x0c.GPIO_Config\x12\x1e\n\tget_value\x18\x03 \x01(\x0e\x32\x0b.GPIO_State\x12\x1e\n\tset_value\x18\x04 \x01(\x0e\x32\x0b.GPIO_State\x12\x10\n\x08\x64\x61ta_buf\x18\x05 \x03(\r*\x1f\n\x08GPIO_NUM\x12\x0c\n\x08GPIO_MAX\x10 \x1a\x05\x92?\x02P\x00*D\n\tGPIO_FUNC\x12\x06\n\x02IN\x10\x00\x12\x07\n\x03OUT\x10\x01\x12\x08\n\x04\x41LT1\x10\x02\x12\x08\n\x04\x41LT2\x10\x03\x12\x08\n\x04\x41LT3\x10\x04\x12\x08\n\x04\x41LT4\x10\x05*#\n\nGPIO_VSSEL\x12\t\n\x05VDDIO\x10\x00\x12\n\n\x06VDDIOH\x10\x01*0\n\x08GPIO_PAD\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07PULL_UP\x10\x01\x12\r\n\tPULL_DOWN\x10\x02*D\n\x0cGPIO_INT_POL\x12\x0b\n\x07\x46\x41LLING\x10\x00\x12\x08\n\x04HIGH\x10\x01\x12\n\n\x06RISING\x10\x02\x12\x07\n\x03LOW\x10\x03\x12\x08\n\x04\x42OTH\x10\x04* \n\nGPIO_State\x12\t\n\x05RESET\x10\x00\x12\x07\n\x03SET\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GPIO_Proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GPIO_NUM._options = None
  _GPIO_NUM._serialized_options = b'\222?\002P\000'
  _GPIO_NUM._serialized_start=320
  _GPIO_NUM._serialized_end=351
  _GPIO_FUNC._serialized_start=353
  _GPIO_FUNC._serialized_end=421
  _GPIO_VSSEL._serialized_start=423
  _GPIO_VSSEL._serialized_end=458
  _GPIO_PAD._serialized_start=460
  _GPIO_PAD._serialized_end=508
  _GPIO_INT_POL._serialized_start=510
  _GPIO_INT_POL._serialized_end=578
  _GPIO_STATE._serialized_start=580
  _GPIO_STATE._serialized_end=612
  _GPIO_CONFIG._serialized_start=35
  _GPIO_CONFIG._serialized_end=173
  _GPIO_PROTO._serialized_start=176
  _GPIO_PROTO._serialized_end=318
# @@protoc_insertion_point(module_scope)
