# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: I2C_Proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fI2C_Proto.proto\x1a\x0cnanopb.proto\"\xaf\x01\n\tI2C_Proto\x12\x13\n\x0bi2c_bus_num\x18\x01 \x02(\r\x12\x13\n\x0bi2c_address\x18\x02 \x02(\r\x12\x0f\n\x07tx_size\x18\x03 \x02(\r\x12\x0f\n\x07rx_size\x18\x04 \x02(\r\x12\x10\n\x08\x64\x61ta_buf\x18\x05 \x03(\r\x12\x1f\n\x07restart\x18\x06 \x01(\x0e\x32\x0e.RestartConfig\x12#\n\tfrequency\x18\x07 \x01(\x0e\x32\x10.FrequencyConfig*\x91\x01\n\x0f\x46requencyConfig\x12\x11\n\rI2C_Freq_100k\x10\x01\x12\x11\n\rI2C_Freq_400k\x10\x02\x12\x0f\n\x0bI2C_Freq_1M\x10\x03\x12\x11\n\rI2C_Freq_3_4M\x10\x04\x12\x10\n\x0cI2C_Freq_10k\x10\x05\x12\x10\n\x0cI2C_Freq_20k\x10\x06\x12\x10\n\x0cI2C_Freq_50k\x10\x07*\x1b\n\x08\x42UF_SIZE\x12\x08\n\x03MAX\x10\xff\x01\x1a\x05\x92?\x02P\x00* \n\rRestartConfig\x12\x07\n\x03off\x10\x00\x12\x06\n\x02on\x10\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'I2C_Proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUF_SIZE._options = None
  _BUF_SIZE._serialized_options = b'\222?\002P\000'
  _FREQUENCYCONFIG._serialized_start=212
  _FREQUENCYCONFIG._serialized_end=357
  _BUF_SIZE._serialized_start=359
  _BUF_SIZE._serialized_end=386
  _RESTARTCONFIG._serialized_start=388
  _RESTARTCONFIG._serialized_end=420
  _I2C_PROTO._serialized_start=34
  _I2C_PROTO._serialized_end=209
# @@protoc_insertion_point(module_scope)
