# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SPI_Proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSPI_Proto.proto\"\xf3\x01\n\tSPI_Proto\x12\x14\n\x03\x63\x66g\x18\x01 \x01(\x0e\x32\x07.config\x12\x17\n\x04\x66stb\x18\x02 \x01(\x0e\x32\t.firstBit\x12\x13\n\x04\x63pol\x18\x03 \x01(\x0e\x32\x05.CPOL\x12\x13\n\x04\x63pha\x18\x04 \x01(\x0e\x32\x05.CPHA\x12\x18\n\x04size\x18\x05 \x01(\x0e\x32\n.DATA_SIZE\x12\x15\n\x05\x63spol\x18\x06 \x01(\x0e\x32\x06.CSPOL\x12\x17\n\x04\x66req\x18\x07 \x01(\x0e\x32\t.BAUDRATE\x12\x0f\n\x07\x62us_num\x18\x08 \x02(\r\x12\x0f\n\x07rx_size\x18\t \x02(\r\x12\x0f\n\x07tx_size\x18\n \x02(\r\x12\x10\n\x08\x64\x61ta_buf\x18\x0b \x03(\r*\x19\n\x06\x63onfig\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01*\x1c\n\x08\x66irstBit\x12\x07\n\x03LSB\x10\x00\x12\x07\n\x03MSB\x10\x01*#\n\x04\x43POL\x12\x0c\n\x08LOWLEVEL\x10\x00\x12\r\n\tHIGHLEVEL\x10\x01*\x1d\n\x04\x43PHA\x12\t\n\x05\x46IRST\x10\x00\x12\n\n\x06SECOND\x10\x01*\"\n\tDATA_SIZE\x12\x08\n\x04\x42YTE\x10\x00\x12\x0b\n\x07HALF_WD\x10\x01*\x1e\n\x05\x43SPOL\x12\t\n\x05LOWEN\x10\x00\x12\n\n\x06HIGHEN\x10\x01*\x86\x01\n\x08\x42\x41UDRATE\x12\r\n\tSPI_24Mhz\x10\x00\x12\r\n\tSPI_12Mhz\x10\x01\x12\x0c\n\x08SPI_6Mhz\x10\x02\x12\x0c\n\x08SPI_3Mhz\x10\x03\x12\x0e\n\nSPI_1P5Mhz\x10\x04\x12\x0e\n\nSPI_750Khz\x10\x05\x12\x0e\n\nSPI_375Khz\x10\x06\x12\x10\n\x0cSPI_187P5Khz\x10\x07')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SPI_Proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG._serialized_start=265
  _CONFIG._serialized_end=290
  _FIRSTBIT._serialized_start=292
  _FIRSTBIT._serialized_end=320
  _CPOL._serialized_start=322
  _CPOL._serialized_end=357
  _CPHA._serialized_start=359
  _CPHA._serialized_end=388
  _DATA_SIZE._serialized_start=390
  _DATA_SIZE._serialized_end=424
  _CSPOL._serialized_start=426
  _CSPOL._serialized_end=456
  _BAUDRATE._serialized_start=459
  _BAUDRATE._serialized_end=593
  _SPI_PROTO._serialized_start=20
  _SPI_PROTO._serialized_end=263
# @@protoc_insertion_point(module_scope)
